name: cloudflared

services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
    - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped

networks:
  edge:
    external: true
    name: edge